Repository thinktocode/GitFit, pull requests merged in 2021-01, with the labels that each got.

#14 BEAUTIFY README BADGES IMPROVE
  README.md
Labels: DWOC, Level-2

#15 Created CODE_OF_CONDUCT.md
  .github/config.yml
  CODE_OF_CONDUCT.md
Labels: DWOC, Level-2

#16 added open-source section to readme
  README.md
Labels: DWOC, Level-2

#17 created pull request template
  .github/pull_request_template.md
Labels: DWOC, Level-1

#19 Created CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: DWOC, Level-1

#20 CONTRIBUTING.md FILE
  CONTRIBUTING.md
  README.md
Labels: DWOC, Level-2

#22 Bug Fix
  app/debug/output-metadata.json
Labels: DWOC, Level-5

#24 Add Contributors Table in README.md #23
  README.md
Labels: DWOC, Level-1

#26 Update README.md
  README.md
Labels: DWOC, Level-1
